### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by Kristinita** [lowliet/sublimetext-StatusBarWeather#1]
### Summary

Plugin not worked. StatusBarWeather not been updated for 3 years, possibly in the Yahoo Weather API during this time there have been changes.
### Expected behavior

Show weather in Status Bar.
### Actual behavior

Not show weather in Status Bar. Output in console:

```
StatusBarWeather | Settings: RSXX1374, c, True | 09:28:20
StatusBarWeather | Cannot fetch weather, check settings
```
### Steps to reproduce

I installed your plugin, I get weather location code for my town on [Weather Location Codes/IDs](https://weather.codes/search/?q=cherkessk) site. My `User\StatusBarWeather.sublime-settings` file:

```
{
    "code": "RSXX1374",
    "debug": true
}

```

Not weather in my Status Bar. I tried to expose the code of any other city, for example, London, but I got the same result.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by lowliet** [comment]
Thanks @Kristinita, that's a very good report - I've just [found out](https://www.igorkromin.net/index.php/2016/03/27/yahoo-effectively-shut-down-its-weather-api-by-forcing-oauth-10-and-crippling-it/) that:

> Yahoo has effectively shut down it's Weather API by forcing everyone to use OAuth 1.0 in order to access its data. Not only has this been done for the YQL API but it also applies to the Weather RSS feed! Previously this has been a public API but as of a few days ago it stopped working completely and requires authorisation

Looks like there are ways around it, but I don't think I will have the time to implement those anytime soon, so if you have any time to spare it would be really appreciated if you could open a pull request with a fix.

Cheers!

**Comment by ildarkhasanshin** [comment]
@lowliet 
#2 

@Kristinita 
1 открыть ../Installed Packages/Status Bar Weather.sublime-package любым архиватором
2 сделать рез. копию, переименовав в самом архиве StatusBarWeather.py в StatusBarWeather.py
3 загрузить в этот архив новый файл https://github.com/ildarkhasanshin/sublimetext-StatusBarWeather/blob/master/StatusBarWeather.py
4 в настройках изменить id на 2120514 (Cherkessk)
5 перезапустить st3

**Comment by Kristinita** [comment]
@ildarkhasanshin , к сожалению, не работает для меня. Погода в Status Bar не показывается, а в консоли при запуске Sublime Text 3 выдаётся следующий stack trace:

```
reloading plugin Status Bar Weather.StatusBarWeather
Traceback (most recent call last):
  File "E:\Sublime Text Build 3126 For Tests\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "E:\Sublime Text Build 3126 For Tests\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "E:\Sublime Text Build 3126 For Tests\Data\Packages\Status Bar Weather\StatusBarWeather.py", line 57
    self._url = "https://query.yahooapis.com/v1/public/yql?format=xml&q=SELECT%20*%20FROM%20weather.forecast%20WHERE%20u=%27{1}%27%20AND%20woeid%20=%20%27{0}%27".format(code, unit)
                                                                                                                                                                                   ^
IndentationError: unindent does not match any outer indentation level
```

---

И как Вы получили значение `2120514`? [Написано](https://weather.codes/), что в Yahoo! Weather используются Weather Location Codes/IDs, где значение для Черкесска — `RSXX1374`.

Спасибо!

**Comment by ildarkhasanshin** [comment]
> как Вы получили значение 2120514

1 https://www.yahoo.com/news/weather
2 нажимаем change location
3 вводим кириллицей черкесск
4 нажимаем на результат поиска - обновляется ссылка страницы

це в пуле было уже
https://github.com/lowliet/sublimetext-StatusBarWeather/pull/2
добавил мануал в readme.md и .sublime-settings

**Comment by ildarkhasanshin** [comment]
> IndentationError: unindent does not match any outer indentation level

пробелы в двух строках были, обновил https://github.com/ildarkhasanshin/sublimetext-StatusBarWeather/blob/master/StatusBarWeather.py

**Comment by Kristinita** [comment]
@ildarkhasanshin , у Вас исправно работает плагин?

У меня данные по погоде редко обновляются. При перезагрузке Sublime Text они обновляются, но потом опять как температура, так и остальные данные могут часами не меняться.

И изредка в Status Bar не отображается никаких погодных данных, и я получаю в консоли `StatusBarWeather | Cannot fetch weather, check settings`.

Спасибо.

**Comment by ildarkhasanshin** [comment]
@Kristinita
сам xml-файл редко обновляется
у меня в todo есть пункты дописать парсеры для гисметео и яндекс.погоды
но все руки не доходят
